<a href="https://colab.research.google.com/github/gloshiii234/PAMCA_TRAINING_MALARIA_GEN-2023/blob/main/Copy_of_Workshop_6_Module_1_Haplotypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![banner](https://github.com/anopheles-genomic-surveillance/anopheles-genomic-surveillance.github.io/blob/master/docs/banner.jpg?raw=1)

***[Workshop 6](about) - Training course in data analysis for genomic surveillance of African malaria vectors***

---

# Module 1 - Haplotypes

**Theme: Data**

In previous workshops we have analysed data on individual genetic variations, such as single nucleotide polymorphisms. This module introduces a new type of genetic variation data called "haplotypes". The benefit of haplotype data is that it conveys the **combinations of mutations** that occur together on the same segment of a DNA sequence. This in turn allows us to study how those DNA sequences are inherited and transmitted between generations. Many novel and powerful methods of analysis are possible with haplotype data, including analyses to detect genome regions under strong positive selection, which we will study in the subsequent modules of this workshop.

## Learning objectives

At the end of this module you will be able to:

* Explain what haplotypes are.
* Explain why haplotypes are useful for vector genomic surveillance.
* Explain how haplotypes are inferred from genotype data (phasing).
* Access haplotype data from MalariaGEN and explain how the data are stored.


## Lecture

### English

In [ ]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/ifk0U0VrHjk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Français

In [ ]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/hcMtMofWxtI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Please note that the code in the cells below might differ from that shown in the video. This can happen because Python packages and their dependencies change due to updates, necessitating tweaks to the code.

## What are haplotypes?

Please see the lecture videos for an explanation of what haplotypes are, why they are useful, and how we infer haplotypes from next-generation sequence data.

## Accessing MalariaGEN haplotype data

MalariaGEN routinely generates haplotype data from whole-genome sequencing of *Anopheles* mosquitoes. These data can be accessed as follows.

### Setup

In [ ]:
!pip install -q --no-warn-conflicts malariagen_data

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.7/131.7 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 58.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 78.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 28.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 79.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.5/302.5 kB 27.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 90.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 13.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 64.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.1/206.1 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
import malariagen_data

In [ ]:
ag3 = malariagen_data.Ag3()
ag3

<MalariaGEN Ag3 API client>
Storage URL             : gs://vo_agam_release/
Data releases available : 3.0
Results cache           : None
Cohorts analysis        : 20230516
AIM analysis            : 20220528
Site filters analysis   : dt_20200416
Software version        : malariagen_data 7.12.0
Client location         : Nevada, US
---
Please note that data are subject to terms of use,
for more information see https://www.malariagen.net/data
or contact data@malariagen.net. For API documentation see 
https://malariagen.github.io/vector-data/ag3/api.html

Haplotype data can be accessed via the `haplotypes()` function. Let's look at the function documentation.

In [ ]:
ag3.haplotypes?

Let's demonstrate this function, accessing haplotype data for a small genome region on chromosome arm 2L from position 2,422,600 to 2,422,700. To keep things simple we'll also only access haplotypes from 20 randomly chosen samples from Cameroon. This function returns an [xarray dataset](../workshop-5/module-1-xarray).

In [ ]:
ds_haps = ag3.haplotypes(
    region="2L:2,422,600-2,422,700",
    analysis="gamb_colu_arab",
    sample_query="country == 'Cameroon'",
    cohort_size=20,
)
ds_haps

<xarray.Dataset>
Dimensions:           (variants: 26, alleles: 2, samples: 20, ploidy: 2)
Coordinates:
    variant_position  (variants) int32 dask.array<chunksize=(26,), meta=np.ndarray>
    variant_contig    (variants) uint8 dask.array<chunksize=(26,), meta=np.ndarray>
    sample_id         (samples) object dask.array<chunksize=(11,), meta=np.ndarray>
Dimensions without coordinates: variants, alleles, samples, ploidy
Data variables:
    variant_allele    (variants, alleles) |S1 dask.array<chunksize=(26, 1), meta=np.ndarray>
    call_genotype     (variants, samples, ploidy) int8 dask.array<chunksize=(26, 3, 2), meta=np.ndarray>
Attributes:
    contigs:   ('2R', '2L', '3R', '3L', 'X')
    analysis:  gamb_colu_arab

In [ ]:
##Obtaining haplotypes from region 3L

dt_haps = ag3.haplotypes(
    region="3L:2,422,600-2,422,700",
    analysis="gamb_colu_arab",
    sample_query="country == 'Cameroon'",
    cohort_size=20,
)
dt_haps


<xarray.Dataset>
Dimensions:           (variants: 11, alleles: 2, samples: 20, ploidy: 2)
Coordinates:
    variant_position  (variants) int32 dask.array<chunksize=(11,), meta=np.ndarray>
    variant_contig    (variants) uint8 dask.array<chunksize=(11,), meta=np.ndarray>
    sample_id         (samples) object dask.array<chunksize=(11,), meta=np.ndarray>
Dimensions without coordinates: variants, alleles, samples, ploidy
Data variables:
    variant_allele    (variants, alleles) |S1 dask.array<chunksize=(11, 1), meta=np.ndarray>
    call_genotype     (variants, samples, ploidy) int8 dask.array<chunksize=(11, 3, 2), meta=np.ndarray>
Attributes:
    contigs:   ('2R', '2L', '3R', '3L', 'X')
    analysis:  gamb_colu_arab

In [ ]:
##Obtaining haplotypes from 3R in Uganda

dr_haps = ag3.haplotypes(
    region="3R:2,422,600-2,422,700",
    analysis="gamb_colu_arab",
    sample_query="country == 'Uganda'",
    cohort_size=20,
)
dr_haps

<xarray.Dataset>
Dimensions:           (variants: 38, alleles: 2, samples: 20, ploidy: 2)
Coordinates:
    variant_position  (variants) int32 dask.array<chunksize=(38,), meta=np.ndarray>
    variant_contig    (variants) uint8 dask.array<chunksize=(38,), meta=np.ndarray>
    sample_id         (samples) object dask.array<chunksize=(20,), meta=np.ndarray>
Dimensions without coordinates: variants, alleles, samples, ploidy
Data variables:
    variant_allele    (variants, alleles) |S1 dask.array<chunksize=(38, 1), meta=np.ndarray>
    call_genotype     (variants, samples, ploidy) int8 dask.array<chunksize=(38, 5, 2), meta=np.ndarray>
Attributes:
    contigs:   ('2R', '2L', '3R', '3L', 'X')
    analysis:  gamb_colu_arab

There are 20 samples and thus 40 haplotypes in this dataset. We also have data for 26 variants (SNPs).

In [ ]:
n_samples = ds_haps.dims["samples"]
n_samples

20

In [ ]:
n_haps = n_samples * 2
n_haps

40

In [ ]:
n_variants = ds_haps.dims["variants"]
n_variants

26

In [ ]:
##Finding variants in 3L in Cameroon

n_variants = dt_haps.dims["variants"]
n_variants


11

In [ ]:
##Finding the number of variants from Uganda

n_variants = dr_haps.dims["variants"]
print("Uganda has %d variants in region 3R" % n_variants)

Uganda has 38 variants in region 3R


The "variant_position" array has data on the genomic coordinates of the SNPs.

In [ ]:
pos = ds_haps["variant_position"].values
pos

array([2422601, 2422606, 2422609, 2422610, 2422611, 2422613, 2422617,
       2422621, 2422625, 2422629, 2422630, 2422634, 2422643, 2422645,
       2422651, 2422652, 2422666, 2422678, 2422680, 2422683, 2422685,
       2422687, 2422688, 2422691, 2422695, 2422697], dtype=int32)

In [ ]:
##Finding the genomic cordinates of variants in Uganda

position = dr_haps["variant_position"].values
position

array([2422602, 2422603, 2422605, 2422606, 2422607, 2422608, 2422609,
       2422611, 2422612, 2422614, 2422620, 2422622, 2422624, 2422625,
       2422627, 2422629, 2422637, 2422638, 2422641, 2422642, 2422645,
       2422646, 2422647, 2422650, 2422651, 2422654, 2422656, 2422659,
       2422660, 2422666, 2422667, 2422670, 2422676, 2422683, 2422689,
       2422694, 2422695, 2422696], dtype=int32)

The "variant_allele" array has the reference and alternate alleles for the SNPs.

In [ ]:
alleles = ds_haps["variant_allele"].values
alleles

array([[b'T', b'A'],
       [b'T', b'G'],
       [b'C', b'T'],
       [b'C', b'A'],
       [b'T', b'A'],
       [b'C', b'T'],
       [b'C', b'A'],
       [b'T', b'G'],
       [b'C', b'A'],
       [b'G', b'A'],
       [b'C', b'A'],
       [b'T', b'C'],
       [b'A', b'G'],
       [b'G', b'A'],
       [b'T', b'C'],
       [b'A', b'T'],
       [b'C', b'T'],
       [b'G', b'T'],
       [b'C', b'G'],
       [b'A', b'C'],
       [b'A', b'G'],
       [b'C', b'A'],
       [b'G', b'T'],
       [b'T', b'A'],
       [b'C', b'T'],
       [b'T', b'A']], dtype='|S1')

In [ ]:
##Obtaining the alleles in Uganda at 3R

allele = dr_haps["variant_allele"].values
allele


array([[b'C', b'T'],
       [b'G', b'A'],
       [b'A', b'G'],
       [b'C', b'A'],
       [b'A', b'G'],
       [b'A', b'T'],
       [b'T', b'G'],
       [b'A', b'C'],
       [b'T', b'C'],
       [b'G', b'A'],
       [b'C', b'T'],
       [b'C', b'T'],
       [b'G', b'A'],
       [b'C', b'T'],
       [b'G', b'A'],
       [b'C', b'T'],
       [b'T', b'G'],
       [b'G', b'C'],
       [b'G', b'A'],
       [b'G', b'T'],
       [b'A', b'T'],
       [b'A', b'T'],
       [b'T', b'G'],
       [b'T', b'G'],
       [b'T', b'G'],
       [b'T', b'A'],
       [b'G', b'A'],
       [b'C', b'T'],
       [b'T', b'C'],
       [b'T', b'C'],
       [b'C', b'T'],
       [b'A', b'C'],
       [b'T', b'G'],
       [b'T', b'C'],
       [b'T', b'A'],
       [b'C', b'T'],
       [b'T', b'A'],
       [b'G', b'T']], dtype='|S1')

In [ ]:
ref = alleles[:, 0]
ref

array([b'T', b'T', b'C', b'C', b'T', b'C', b'C', b'T', b'C', b'G', b'C',
       b'T', b'A', b'G', b'T', b'A', b'C', b'G', b'C', b'A', b'A', b'C',
       b'G', b'T', b'C', b'T'], dtype='|S1')

In [ ]:
##Obtaining the reference alleles from Uganda

reference = allele[:, 0]
reference

array([b'C', b'G', b'A', b'C', b'A', b'A', b'T', b'A', b'T', b'G', b'C',
       b'C', b'G', b'C', b'G', b'C', b'T', b'G', b'G', b'G', b'A', b'A',
       b'T', b'T', b'T', b'T', b'G', b'C', b'T', b'T', b'C', b'A', b'T',
       b'T', b'T', b'C', b'T', b'G'], dtype='|S1')

In [ ]:
alt = alleles[:, 1]
alt

array([b'A', b'G', b'T', b'A', b'A', b'T', b'A', b'G', b'A', b'A', b'A',
       b'C', b'G', b'A', b'C', b'T', b'T', b'T', b'G', b'C', b'G', b'A',
       b'T', b'A', b'T', b'A'], dtype='|S1')

In [ ]:
#Obtaining the alternate alleles from Uganda

alternative = allele[:, 1]
alternative

array([b'T', b'A', b'G', b'A', b'G', b'T', b'G', b'C', b'C', b'A', b'T',
       b'T', b'A', b'T', b'A', b'T', b'G', b'C', b'A', b'T', b'T', b'T',
       b'G', b'G', b'G', b'A', b'A', b'T', b'C', b'C', b'T', b'C', b'G',
       b'C', b'A', b'T', b'A', b'T'], dtype='|S1')

The haplotypes themselves are stored in the "call_genotype" array. The shape of this array is (number of variants, number of samples, number of haplotypes per sample).

In [ ]:
gt = ds_haps["call_genotype"].values
gt.shape

(26, 20, 2)

In [ ]:
##Getting the shape of the array from Uganda

dt = dr_haps["call_genotype"].values
dt.shape


(38, 20, 2)

This array uses the numeric encoding for the alleles. We can see that by inspecting its dtype and also inspecting the data values.

In [ ]:
gt.dtype

dtype('int8')

In [ ]:
gt

array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       ...,

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int8)

In [ ]:
##Visualizing the shape of the array with Ugandan haplotypes

dt

array([[[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       ...,

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        ...,
        [0, 0],
        [0, 0],
        [0, 0]]], dtype=int8)

The basic numpy representation of this array is a bit hard to understand, so to help build our intuition of this data structure let's make a simple plotting function to visualise haplotypes.

In [ ]:
def plot_haplotypes(
    ds,
    hide_text=False,
    hide_non_seg=False,
):
    import plotly.express as px
    import allel

    # convert to 2D array of haplotypes
    pos = ds["variant_position"].values
    gt = ds["call_genotype"].values
    ht = gt.reshape(gt.shape[0], -1)

    # size rows and columns
    if hide_text:
        # can make smaller because text not shown
        row_height = 8
        col_width = 5
    else:
        # make a bit bigger so we can see the text
        row_height = 14
        col_width = 12

    # deal with non-segregating sites
    if hide_non_seg:
        ac = allel.HaplotypeArray(ht).count_alleles(max_allele=1)
        loc_seg = ac.is_segregating()
        ht = ht[loc_seg]

    # plot a heatmap
    fig = px.imshow(
        ht.T,
        text_auto=not hide_text,
        labels=dict(
            x="Variants",
            y="Haplotypes",
        ),
        width=ht.shape[0] * col_width + 200,
        height=ht.shape[1] * row_height + 200,
        zmin=0,
        zmax=0,
        color_continuous_scale="greys",
        template="simple_white",
        aspect="auto"
    )

    # visual styling
    fig.update_layout(
        coloraxis_showscale=False,
        plot_bgcolor="#cccccc",
    )
    fig.update_traces(xgap=0, ygap=1)
    fig.update_xaxes(tickvals=[])
    fig.update_yaxes(tickvals=[])

    return fig

This function will visualise haplotypes as a heatmap, with haplotypes as rows and variants as columns. A reference allele has a white background, and an alternate allele has a black background.

Let's use the function to visualise the haplotypes we accessed above.

In [ ]:
plot_haplotypes(ds_haps)

In [ ]:
##Visualizing the haplotypes from Uganda

plot_haplotypes(dt_haps)


In this set of haplotype data we can see there are only two variants which are segregating in this set of samples. All the other variants are non-segregating, which means all haplotypes carry the same allele (in this case a "0" meaning the reference allele).

The non-segregating variants are not particularly informative, so let's hide them.

In [ ]:
plot_haplotypes(ds_haps, hide_non_seg=True)

We can see now that within this genome region, and within this set of 20 samples, we have two segregating sites and three unique haplotypes.

## Well done!

Hopefully this module has been a useful introduction to haplotype data. There are no practical exercises for this module, but you might like to launch this notebook for yourself, and try running the code examples above, or changing them to load data from a different genome region or a different set of samples.